
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jul 06 22:57:45 CEST 2015
//----------------------------------------------------

package semantica;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int BLOQUEAPERTURA = 22;
  public static final int DISTINTO = 17;
  public static final int PARENTESISCIERRE = 32;
  public static final int ANGULOCIERRE = 29;
  public static final int PROGRAMA = 2;
  public static final int ENTERO = 37;
  public static final int SI = 34;
  public static final int CASE = 19;
  public static final int INTEGER = 5;
  public static final int PUNTOCOMA = 7;
  public static final int IGUAL = 4;
  public static final int OPERADOROR = 12;
  public static final int SINO = 35;
  public static final int OPERADORRESTA = 9;
  public static final int MIENTRAS = 33;
  public static final int BEGIN = 24;
  public static final int ENDPROGRAMA = 3;
  public static final int BLOQUECIERRE = 23;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 16;
  public static final int OPERADORAND = 13;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int ANGULOAPERTURA = 28;
  public static final int MENOR = 15;
  public static final int PARENTESISAPERTURA = 31;
  public static final int OPERADORDIVISION = 11;
  public static final int SWITCH = 18;
  public static final int MAYOR = 14;
  public static final int CORCHETECIERRE = 26;
  public static final int IGUALLOGICO = 21;
  public static final int FUNC = 27;
  public static final int OPERADORSUMA = 8;
  public static final int DEFAULT = 20;
  public static final int BOOLEANO = 38;
  public static final int CORCHETEAPERTURA = 25;
  public static final int OPERADORMULTIPLICACION = 10;
}

